### ISSUE TITLE
Remove length function call on loop.

### ISSUE THREAD

**Issue by ashraf789** [moshiurse/ds_algo#2]
First of all good and clean code. But I have noticed a line of code that could be a little better. 

To calculate array length takes some time therefore it's good practice to call them before the loop start. 
![image](https://user-images.githubusercontent.com/13873490/108832558-46820080-75fe-11eb-82b3-7492212cbdba.png)

**Comment by moshiurse** [comment]
Thanks @ashraf789 for your feedback. 
Fixed it .  See : 45b303e
